### ISSUE TITLE
Tarball missing for 10 days

### ISSUE THREAD

**Issue by jrmarino** [kyz/libmspack#17]
On the main website https://www.cabextract.org.uk/libmspack/, this is printed: 
"The latest release of libmspack is libmspack 0.7alpha, released on 25 July 2018."
which has a link to "https://www.cabextract.org.uk/libmspack/libmspack-0.7alpha.tar.gz"

which does not exist.
```
Not Found
The requested URL /libmspack/libmspack-0.7alpha.tar.gz was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

I thought maybe the file had to get re-rolled, but after 10 days, either you guys aren't aware the file is missing or there's a major issue in which an adjustment of the website is necessary, I would think.

If it's just a bad link, can you fix it?

**Comment by kyz** [comment]
The problem is my own ISP is intentionally deleting the release, because my ISP are idiots, and they scan all files uploaded for "viruses", and ClamAV is telling them the file `test/test_files/cabd/lzx-premature-matches.cab` is a BC.Legacy.Exploit.CVE_2012_1458-1 "virus"

In other words, the test file I intentionally include to prove that libmspack is no longer exploitable by a 6 year old exploit, is still in ClamAV's database as something that can be used to exploit 6 year old copies of ClamAV, and therefore that's a "virus", which will continually block and prevent the release of the latest libmspack 0.7

Thanks a bunch, ClamAV.

**Comment by jrmarino** [comment]
now there's a valid use of a *facepalm*

**Comment by kyz** [comment]
libmspack 0.7.1alpha has been released. The only change over libmspack 0.7alpha is that it obfuscates the file which ClamAV objects to, so that ClamAV won't claim the release is "infected".

The file is deobfuscated during the build process, so libmspack can still be tested and proven not vulnerable to this old vulnerability.

**Comment by jrmarino** [comment]
thanks!

**Comment by micah-at-talos** [comment]
Sorry about that Stuart!  I think we had a similar issue back in the day (long before my time) with the non-malicious test samples we use in unit testing.  Ours are also generated now to prevent ClamAV from flagging its own tarball.

By the way, I'd like to collaborate more closely with you in the future, particularly with regards to vulnerability reports and such.  Feel free to PM me on Twitter (@0xC0000063) or by email (micasnyd -at- cisco -dot- com).

**Comment by Whissi** [comment]
This doesn't work:
```
sed s/lzxc/LZXC/ /var/tmp/portage/dev-libs/libmspack-0.7.1_alpha/work/libmspack-0.7.1alpha/test/test_files/chmd/cve-2015-4467-reset-interval-zero.chm.LZXC-is-lzxc >test/test_files/chmd/cve-2015-4467-reset-interval-zero.chm
/bin/sh: test/test_files/chmd/cve-2015-4467-reset-interval-zero.chm: No such file or directory
make[1]: *** [Makefile:1358: test/test_files/chmd/cve-2015-4467-reset-interval-zero.chm] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-libs/libmspack-0.7.1_alpha/work/libmspack-0.7.1alpha-abi_x86_64.amd64'
make: *** [Makefile:524: all] Error 2
```

**Comment by jrmarino** [comment]
Which has nothing to do with the original issue though.  Open a new issue next time ...
