### ISSUE TITLE
build fails on macos

### ISSUE THREAD

**Issue by thierryba** [kyz/libmspack#40]
when I go to libmspack and so sh rebuild.sh, I'm getting

mspack/oabd.c:375:12: error: conflicting types for 'copy_fh'
static int copy_fh(struct mspack_system *sys, struct mspack_file *infh,
           ^
mspack/oabd.c:37:12: note: previous declaration is here
static int copy_fh(struct mspack_system *sys, struct mspack_file *infh,
           ^
1 error generated.

**Comment by kyz** [comment]
You should find it works correctly with the release at https://www.cabextract.org.uk/libmspack/

Your problem has nothing to do with macos. Your problem is you are too used to the idioms of the third-party website (github) that currently hosts the libmspack source code.

* https://github.com/kyz/libmspack/issues/29#issuecomment-485724178
* https://github.com/kyz/libmspack/issues/30#issuecomment-485773039
* https://github.com/kyz/libmspack/issues/33#issuecomment-593933346
* https://github.com/kyz/libmspack/issues/37#issuecomment-632742929
