### ISSUE TITLE
MSZIP Compress?

### ISSUE THREAD

**Issue by samsonsite1** [kyz/libmspack#7]
I see that mszipc.c is not implemented yet.  In the source code, it's mention that "MSZIP is equivalent to the deflate method".   Deflate is part of the zlib library.

If deflate() can be used to decompress MSZIP files, is the opposite true as well?  Can the zlib's compress() function be used to create a MSZIP compressed file?  If so, what's stopping you from implementing mszipc.c?

**Comment by kyz** [comment]
It's possible deflate() could be used, the format used in CAB files varies only a little.

However, one of the goals of libmspack is to not require any other libraries, not even the standard C library, which is why any mszipc.c implementation should stand alone.

From https://cabextract.org.uk/libmspack/
> **No dependencies on other libraries:** The code stands on its own. zlib is not required. Even the standard C library can be avoided. This can be very useful for embedded systems
